# Site settings
title: Nathan Thoumine - Workout
email: thoum.nathan@gmail.com
author:
  name: Nathan Thoumine
  email: thoum.nathan@gmail.com
  links:
    - github: deicidia
    - linkedin: nathan-thoumine

description: >-
  Programme d'entraînement et suivi sportif - Coach & Tracker Workout.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://deicidia.github.io" # the base hostname & protocol for your site
image: /images/blog_card.png # Default social sharing image for LinkedIn/Twitter
twitter_username: ThoumNth 
github_username:  deicidia
lang: fr
locale: fr_FR

# Social sharing image
social:
  name: Nathan Thoumine
  links:
    - https://github.com/deicidia
    - https://www.linkedin.com/in/nathan-thoumine/
    - https://x.com/ThoumNth

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SASS configuration
sass:
  sass_dir: _sass
  style: compressed